fix: Set NodeJS v14 as the oldest supported engine version
dotenv v16.4.3 can't be used with Node 12 because the change introduced in the PR https://github.com/motdotla/dotenv/pull/805 contains an optional chaining operator that is supported by NodeJS starting from v14, thus running it with v12 engine version results in the
```js
  if (options?.encoding) {
              ^
SyntaxError: Unexpected token '.'
```
exception.

Considering that Node v12 has reached EOL I assume it's better to set v14 as the oldest version constraint.